import { test as base, Browser, BrowserContext } from '@playwright/test';
import path from 'path';

export type AuthContexts = {
  patientContext: BrowserContext;
  doctorContext: BrowserContext;
  adminContext: BrowserContext;
};

type Role = 'patient' | 'doctor' | 'admin';

async function contextForRole(browser: Browser, role: Role): Promise<BrowserContext> {
  return browser.newContext({ storageState: path.join(__dirname, '../../.auth', `${role}.json`) });
}

/**
 * Auth fixture — provides browser contexts pre-loaded with role-specific storageState.
 * The storageState files are generated by auth.setup.ts.
 */
export const authFixtures = base.extend<AuthContexts>({
  patientContext: async ({ browser }, use) => {
    const ctx = await contextForRole(browser, 'patient');
    await use(ctx);
    await ctx.close();
  },

  doctorContext: async ({ browser }, use) => {
    const ctx = await contextForRole(browser, 'doctor');
    await use(ctx);
    await ctx.close();
  },

  adminContext: async ({ browser }, use) => {
    const ctx = await contextForRole(browser, 'admin');
    await use(ctx);
    await ctx.close();
  },
});
